apiVersion: v1
kind: Service
metadata:
  name: tomcat-test-green
spec:
  selector:
    app: green-app
    env: green
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer